---

- include: install_debian.yml
  when: ansible_os_family == 'Debian'
- include: install_redhat.yml
  when: ansible_os_family == 'RedHat'
- include: config.yml
- include: create.yml
- include: copy.yml
