---
galaxy_info:
  author: franklin
  company: We Are Interactive
  description: Installs and configures nginx
  min_ansible_version: 1.6
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - All
  categories:
    - system
# List your role dependencies here, one per line. Only
# dependencies available via galaxy should be listed here.
# Be sure to remove the '[]' above if you add dependencies
# to this list.
dependencies:
  - franklinkim.openssl
  - franklinkim.htpasswd
